Disable test, because sometimes it cause IOException under windows
Exception is thrown when IDE requests thread tries to acquire a lock:
java.io.IOException: Access is denied
    at java.io.WinNTFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:850)
    at org.eclipse.jgit.storage.file.LockFile.lock(LockFile.java:127)
    at jetbrains.buildServer.buildTriggers.vcs.git.tests.GitVcsSupportTest$11.run(GitVcsSupportTest.java:1083)
    at java.lang.Thread.run(Thread.java:595)